1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns


In [32]:
import numpy as np


In [2]:
vivek = np.random.randint(1,100, (3,3 ))
print(vivek)

[[48 14  4]
 [76 75 51]
 [44 40 71]]


2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [9]:
arr = np.array(range(10))
arr2X5 = arr.reshape(2,5)
print(arr2X5)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
arr5X2 = arr2X5.reshape(5,2)
print(arr5X2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [11]:
arr4X4 = np.random.random((4,4))
print(arr4X4)

[[0.48630846 0.5392204  0.864656   0.48335994]
 [0.4066141  0.92907737 0.29441076 0.91577021]
 [0.67124844 0.90865268 0.67168678 0.82193924]
 [0.39249114 0.99544322 0.06295661 0.2846357 ]]


In [19]:
arr6X6 = np.pad(arr4X4, pad_width=1, mode='constant', constant_values=0)
print(arr6X6)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.48630846 0.5392204  0.864656   0.48335994 0.        ]
 [0.         0.4066141  0.92907737 0.29441076 0.91577021 0.        ]
 [0.         0.67124844 0.90865268 0.67168678 0.82193924 0.        ]
 [0.         0.39249114 0.99544322 0.06295661 0.2846357  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [22]:
arr1 = np.arange(10,61, 5)
print(arr1)

[10 15 20 25 30 35 40 45 50 55 60]


5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [29]:
arr_str = np.array(['python', 'numpy', 'pandas'])
arr_str_upper = np.char.upper(arr_str)
print(arr_str_upper)

['PYTHON' 'NUMPY' 'PANDAS']


In [26]:
arr_str_lower = np.char.lower(arr_str)
print(arr_str_lower)

['python' 'numpy' 'pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [34]:
word = np.array(["Vivek", "Kumar"])
str_space = np.char.join(" ", word)
print(str_space)

['V i v e k' 'K u m a r']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [35]:
arr = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])
arr_add = np.add(arr, arr2)
print(arr_add)

[[ 8 10 12]
 [14 16 18]]


In [36]:
arr_sub = np.subtract(arr, arr2)
print(arr_sub)

[[-6 -6 -6]
 [-6 -6 -6]]


In [38]:
arr_mul = arr*arr2
print(arr_mul)

[[ 7 16 27]
 [40 55 72]]


In [40]:
arr_div = np.divide(arr, arr2)
print(arr_div)

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [41]:
arr_identity = np.eye(5,5)
print(arr_identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [42]:
arr_diag = np.diagonal(arr_identity)
print(arr_diag)

[1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array

In [44]:
rand_100 = np.random.randint(0, 1000, 100)
print(rand_100)

[570 545 184 815 571 101 608  42 618 573 204 534 479 667   6 406 732 655
 398  14 715  92 119  48 938 407 850 930 999 672 801 572 723 523 636 373
 784 579 771 681 233 325 365 430 476 650 991 296  36 989 773  16 264 998
 449 495 449 332 218 141 695 490 788 174   6 579 112 922 941 100 945 376
 808 366 728 469 101 943  60 920 580 901 279 239 770 563 883 709 477 811
  35  87 921 905 862 878 791 336 144 494]


In [48]:
for num in rand_100:
  for i in range(2, num):
    if num % i == 0:
      break
  else:
    print(num)

571
101
479
523
373
233
991
773
449
449
941
101
239
563
883
709
811


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages

In [52]:
temp = np.random.randint(20, 40, 28)
tem_weekly = temp.reshape(4,7) #reshaping for a month with 4 rows(week) and 7(days)
print(tem_weekly)

[[24 36 21 34 37 28 20]
 [36 35 21 32 36 29 33]
 [32 39 26 36 25 37 22]
 [27 27 23 28 31 30 32]]


In [53]:
temp_avg_weekly = np.mean(tem_weekly, axis = 1)
print(temp_avg_weekly)


[28.57142857 31.71428571 31.         28.28571429]
